source 'https://github.com/CocoaPods/Specs.git'
pod 'MWPhotoBrowser'
pod 'AWSCore'
pod 'AWSAutoScaling'
pod 'AWSCloudWatch'
pod 'AWSDynamoDB'
pod 'AWSEC2'
pod 'AWSElasticLoadBalancing'
pod 'AWSKinesis'
pod 'AWSLambda'
pod 'AWSMachineLearning'
pod 'AWSMobileAnalytics'
pod 'AWSS3'
pod 'AWSSES'
pod 'AWSSimpleDB'
pod 'AWSSNS'
pod 'AWSSQS'
pod 'AWSCognito'

pod 'EAIntroView'
pod 'SMPageControl'
pod 'RSKImageCropper'

pod 'Google-API-Client/Drive'


pod 'SVProgressHUD'
pod 'CocoaLumberjack'
pod 'RSBarcodes'